[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "../netlify/functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
